volumes:
  db:

services:
  api:
    container_name: api
    image: api:1.0.0
    build:
      context: .
      target: base
    user: node
    command: sh -c "npm install && ${START_COMMAND}"
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    volumes:
      - .:/usr/src/app
    restart: unless-stopped

  postgres:
    container_name: postgres
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - ${DEFAULT_DATABASE_PORT}:${DEFAULT_DATABASE_PORT}
    environment:
      POSTGRES_USER: ${DEFAULT_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DEFAULT_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEFAULT_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data